CREATE TABLE IF NOT EXISTS contact_inquiries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    status ENUM('NEW', 'READ', 'ARCHIVED') DEFAULT 'NEW',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
